name: CI Pipeline
on:
  pull_request:
    branches:
      - main

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.16.3'
      - name: Package linting
        run: |
          npm ci
          npm run lint

  testing:
    name: Testing
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.16.3'
      - name: Package testing
        run: |
          npm ci
          npm test